### PR TITLE
Add slug to menu item object

### PR DESCRIPTION
**Pull request by beltranrengifo**

### CODE REVIEW

**Comment by thebatclaudio** [comment]
Hello @beltranrengifo,
I will merge this pull request and release a new plugin's version ASAP.
Thank you for your contribute! 👍

**Review by thebatclaudio — APPROVED** [review]

**Comment by beltranrengifo** [comment]
> Hello @beltranrengifo,
> I will merge this pull request and release a new plugin's version ASAP.
> Thank you for your contribute! 👍

Glad to help :)
Thank you!

**Comment by thebatclaudio** [comment]
Hi @beltranrengifo,
I released 0.7.2 version of the plugin!

**Comment by beltranrengifo** [comment]
> Hi @beltranrengifo,
> I released 0.7.2 version of the plugin!

Hi @thebatclaudio 
Thank you, gonna update the plugin!

**Comment by thebatclaudio** [comment]
Hi @beltranrengifo,
if you send me your Wordpress.org username I'll add you in plugin's contributors!

**Comment by beltranrengifo** [comment]
Hi Claudio,
nice! my user is beltranrengifo

Thanks!

**Pull request merged**
