### PR TITLE
Allowing numeric values in menu slug regexp

### PR DESCRIPTION
**Pull request by joshuaslate**
Firstly, thank you for putting this library together.

I have been making use of it for a project, and I ran into an issue. I have menu slugs that include numbers (footer-col1-menu, for example), and was getting 404s when attempting to query for them. This pull request fixes that issue.

Cheers,

Josh

### CODE REVIEW

**Comment by joshuaslate** [comment]
CC: @thebatclaudio

**Comment by thebatclaudio** [comment]
Hi, thank you for using our plugin and for your pull request. 
I'm going to release this new version soon

**Comment by thebatclaudio** [comment]
Hi @joshuaslate,
if you send me your Wordpress.org username I'll add you in plugin's contributors!

**Comment by joshuaslate** [comment]
Hi @thebatclaudio, cool, thanks!

I think it's joshuaslatedesign. Maybe just joshuaslate.

**Pull request merged**
